### PR TITLE
HTML lang and formatting

### PR DESCRIPTION
**Pull request by kaitlinnewson**
This PR sets the HTML lang attribute based on the locale, and also cleans up some formatting/indentation in the HTML and CSS files.

### CODE REVIEW

**Comment by qqmyers** [comment]
@kaitlinnewson - thanks! Can you make a PR against the dev branch (which I've just restored after accidentally having it get deleted with the last merge :-)) instead? Since people use these live via github.io, I/we're trying to give some warning before any update and/or to let people test from the dev branch prior to updating master.

**Comment by kaitlinnewson** [comment]
@qqmyers Done!

**Comment by qqmyers** [comment]
@kaitlinnewson - if you want this deployed asap (which would be fine), let me know and I can announce the update and give people a few days notice. If not, or when you do, let me know - I might wait a while for additional changes.

**Comment by kaitlinnewson** [comment]
No rush - I'm hoping to submit some accessibility improvements soon too FYI!

**Pull request merged**
