### PR TITLE
Translation of dataverse-previewers #17

### PR DESCRIPTION
**Pull request by juancorr**
This pull request is to request the translation of the dataverse-previewers . We have used the jquery.i18n library https://github.com/wikimedia/jquery.i18n which have a dual GPL / MIT license: https://github.com/wikimedia/jquery.i18n/issues/136 .

### CODE REVIEW

**Comment by juancorr** [comment]
Thanks @qqmyers . 

- _The current Dataverse release..._ . I will check how it works. I will tell you if I found some problem.
- _The CSV previewer has been renamed to 'Spreadsheet' ..._ . Yes I have been included the new spreadsheet previewer and the old csv. I had deleted the CSVPreview.html file, but I have forgotten delete the csv.js. Now It is done
- _The TextPreviewer includes the json files ..._ . I had begun the translation with the TextPreviewer and I has forgot these two lines. They are not needed and now they are deleted.

**Comment by pdurbin** [comment]
Related: Translate dataverse-previewers #17

**Comment by kaitlinnewson** [comment]
Hi all, are there any updates on this PR? We're interested in working on a French translation for this and are hoping to use the work in this PR to get started.

**Comment by qqmyers** [comment]
@kaitlinnewson - I think the main thing I was waiting on was an additional change to use the Dataverse locale information rather than having a separate list of language options in the previewer page (and for embedded previews on the file pages). If @juancorr doesn't have the time to make that update, I may be able to , or someone else from the community might be able to help out.  Regardless, I'm sure this will go forward in some form, so if you have/will have another translation, at a minimum I can go ahead and make a separate branch that you can submit it to. (And anyone who  wanted to use that branch before the i18n work is merged into the default branch (being used live by some Dataverse instances) could do so.)

**Comment by juancorr** [comment]
Hi @kaitlinnewson <https://github.com/kaitlinnewson>,

  You can find the translation code related to this PR and the Spanish
translation here:
https://github.com/Consorcio-Madrono/dataverse-previewers/tree/translation
https://github.com/Consorcio-Madrono/dataverse-previewers/tree/translation/previewers/i18n


  We have tested it with Dataverse 4.11, but latest Dataverse versions have
a greater integration. I am sorry but @qqmyers is right. I won't have time
next months to continue this development, but I think that finish it won't
be too difficult.

**Comment by qqmyers** [comment]
@juancorr - could you make a pull request for this work against the new develop branch? As discussed in https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/issues/40 I've created a separate branch so that 'master' is what's deployed through github.io and the develop branch will be where we merge contributions and test before pushing them out. 

Once you do that, I'll merge your work and @kaitlinnewson can go ahead and work on a French translation as a PR to 'develop'.

**Comment by juancorr** [comment]
@qqmyers, it is done:
https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/pull/41

Juan Corrales

**Comment by qqmyers** [comment]
Going to close without merging since we've accepted the PR to the develop branch ( #41 )

**Comment by qqmyers** [comment]
I updated what @juancorr  sent to use the localCode from Dataverse and removed the buttons which were no longer needed. I also made a quick update to move the previewer-specific translations into the previewer's custom js file, and merged some changes from the master branch, etc. 

@kaitlinnewson   - the develop branch should now being doing translations based on the localeCode being sent by Dataverse. I think all you need to do to create another translation is to provide the appropriate previewers/i18n/\<code\>/json file in a PR. 

@juancorr  - note I found two more strings to translate - "File uploaded on", which I was able to translate via Google, and the long error message, which I didn't want to attempt on Google. For now, the error remains in English, but if you let me know what it should be, I can add it (or make a PR).

If anyone wants to test:
Since the develop branch is not available via github.io, the way I tested (lightly) was to download the repository as a zip and dropping the unzipped version in Dataverse (a dataverse-previewers folder in the same dir as all of Dataverse's .xhtml files) and modifying the toolUrl from what's on the readme page to point to my local machine (e.g. https://dv.dev-aws.qdr.org/dataverse-previewers/previewers/TextPreview.html for the text Previewer). With that choice of location and toolUrl, all of the script paths, etc. work.

**Comment by juancorr** [comment]
@qqmyers, the translation could be:
"errorText" : "Inténtelo de nuevo por favor. El problema más común es que
su sesión haya caducado. Si el problema continúa puede contactar con el
equipo de soporte de su repositorio de datos. Por favor, indique los
códigos de estado que encontrará al final de este mensaje."

  Thanks, your test method is much easier than mine. I have installed
Apache and managed access permission.

Juan Corrales

**Pull request closed without merging**
